modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="simplyseasons"
    version="${file.jarVersion}"
    displayName="Simply Seasons"
    authors="joshiejack"
    description='''Spring, Summer, Autumn, Winter and more!'''
[[dependencies.simplyseasons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="botanypots"
    mandatory=false
    versionRange="[1.16.5-7.1.20,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="morpheus"
    mandatory=false
    versionRange="[1.16.5-4.2.70,)"
    ordering="AFTER"
    side="BOTH"