modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="simplyseasons"
    version="${file.jarVersion}"
    displayName="Simply Seasons"
    authors="joshiejack"
    description='''Spring, Summer, Autumn, Winter and more!'''
[[dependencies.simplyseasons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplyseasons]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.2.0-11,)"
    ordering="NONE"
    side="BOTH"